# Generated by Django 4.1.9 on 2023-05-31 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("axians_netbox_pdu", "0002_pdustatus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pduconfig",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="pdustatus",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
